"""empty message

Revision ID: 3b5d77dbd2f6
Revises: 3998ce627184
Create Date: 2018-04-21 06:05:07.456750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b5d77dbd2f6'
down_revision = '3998ce627184'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('borrows', sa.Column('date_borrowed', sa.DateTime(), nullable=True))
    op.add_column('borrows', sa.Column('due_date', sa.DateTime(), nullable=True))
    op.add_column('borrows', sa.Column('return_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('borrows', 'return_time')
    op.drop_column('borrows', 'due_date')
    op.drop_column('borrows', 'date_borrowed')
    # ### end Alembic commands ###
