"""empty message

Revision ID: 5a30632949cf
Revises: d654caa492be
Create Date: 2018-04-16 06:04:07.435272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a30632949cf'
down_revision = 'd654caa492be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('histories')
    op.drop_constraint('books_user_id_fkey', 'books', type_='foreignkey')
    op.drop_column('books', 'user_id')
    op.add_column('borrows', sa.Column('book_title', sa.String(), nullable=True))
    op.add_column('borrows', sa.Column('return_status', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'borrows', 'books', ['book_title'], ['book_title'])
    op.create_unique_constraint(None, 'users', ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'borrows', type_='foreignkey')
    op.drop_column('borrows', 'return_status')
    op.drop_column('borrows', 'book_title')
    op.add_column('books', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('books_user_id_fkey', 'books', 'users', ['user_id'], ['user_id'])
    op.create_table('histories',
    sa.Column('borrow_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('return_status', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.book_id'], name='histories_book_id_fkey'),
    sa.ForeignKeyConstraint(['borrow_id'], ['borrows.borrow_id'], name='histories_borrow_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='histories_user_id_fkey'),
    sa.PrimaryKeyConstraint('borrow_id', name='histories_pkey')
    )
    # ### end Alembic commands ###
