"""empty message

Revision ID: a0fcd95500f7
Revises: 3b5d77dbd2f6
Create Date: 2018-04-24 14:49:25.516318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0fcd95500f7'
down_revision = '3b5d77dbd2f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'authors',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('books', 'book_title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('books_book_id_key', 'books', type_='unique')
    op.drop_constraint('borrows_borrow_id_key', 'borrows', type_='unique')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint('borrows_borrow_id_key', 'borrows', ['borrow_id'])
    op.create_unique_constraint('books_book_id_key', 'books', ['book_id'])
    op.alter_column('books', 'book_title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('books', 'authors',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
