"""empty message

Revision ID: eceb093052f4
Revises: 8a54c4983f9f
Create Date: 2018-04-28 15:56:51.954745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eceb093052f4'
down_revision = '8a54c4983f9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('limited_monthly_3', sa.Boolean(), nullable=True),
    sa.Column('limited_monthly_6', sa.Boolean(), nullable=True),
    sa.Column('unlimited_monthly_3', sa.Boolean(), nullable=True),
    sa.Column('unlimited_monthly_6', sa.Boolean(), nullable=True),
    sa.Column('limited_yearly_3', sa.Boolean(), nullable=True),
    sa.Column('limited_yearly_6', sa.Boolean(), nullable=True),
    sa.Column('unlimited_yearly_3', sa.Boolean(), nullable=True),
    sa.Column('unlimited_yearly_6', sa.Boolean(), nullable=True),
    sa.Column('expiry', sa.DateTime(), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('charges', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('plan_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plans')
    # ### end Alembic commands ###
